guiline/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('me/', views.inbox, name='inbox'),
    path('me/<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new')
]

guiline/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from . forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name="login"),
]

guiline/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index' )
]

guiline/guiline/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include('core.urls')),
    path("items/", include('item.urls')),
    path("inbox/", include('conversation.urls')),
    path("dashboard/", include('dashboard.urls')),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guiline/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.browseItems, name='browseItems'),
    path('new/', views.new_item, name='new_item'),
    path("<int:pk>/", views.detail, name='detail'),
    path("<int:pk>/delete/", views.delete, name='delete'),
    path("<int:pk>/edit/", views.edit, name='edit'),
]

guiline/core/models.py
from django.db import models

# Create your models here.

guiline/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your Username",
        "class": "w-full py-4 px-6 rounded-l"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your Password",
        "class": "w-full py-4 px-6 rounded-l"
    }))
    
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your Username",
        "class": "w-full py-4 px-6 rounded-l"
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        "placeholder": "Your Email",
        "class": "w-full py-4 px-6 rounded-l"
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your Password",
        "class": "w-full py-4 px-6 rounded-l"
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Retype Password",
        "class": "w-full py-4 px-6 rounded-l"
    }))
    

guiline/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:9]
    categories = Category.objects.all()
    context = {
        "categories" : categories,
        "items" : items,
    }
    return render(request, 'core/index.html', context)

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupForm()
        
    context = {
        "form" : form
    }
    return render(request, "core/signup.html", context)

guiline/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock  %} | Guiline</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">

        <a href="/" class="text-xl font-semibold">Guiline</a>

        <div class="space-x-6">
            <a href="{% url 'item:new_item' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="{% url 'item:browseItems' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif %}

        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        
        {% endblock  %}
    </div>

    <!--Footer container-->
    <footer class="mt-9 bg-neutral-200 text-center text-white dark:bg-neutral-600">
        <div class="pt-9 mb-9 flex justify-center items-center">
            <a href="#!" class="mr-9 text-neutral-800 dark:text-neutral-200">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-4 w-4"
                    fill="currentColor"
                    viewBox="0 0 24 24">
                    <path
                        d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z" />
                </svg>
            </a>
            <a href="#!" class="mr-9 text-neutral-800 dark:text-neutral-200">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-4 w-4"
                    fill="currentColor"
                    viewBox="0 0 24 24">
                    <path
                        d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z" />
                </svg>
            </a>
            <a href="#!" class="text-neutral-800 dark:text-neutral-200">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-4 w-4"
                    fill="currentColor"
                    viewBox="0 0 24 24">
                    <path
                        d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                </svg>
            </a>
        </div>

        <div class=" flex justify-center items-center border-t border-neutral-500" >
            <ul class="py-6">
                <li class="pb-3"><a href="#" class="text-lg hover:text-teal-700">Home</a></li>
                <li class="pb-3"><a href="{% url 'core:contact' %}" class="text-lg hover:text-teal-700">Contact</a></li>
                <li class="pb-3"><a href="#" class="text-lg hover:text-teal-700">Privacy</a></li>
                <li class="pb-3"><a href="#" class="text-lg hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>

        <div class="bg-neutral-300 p-4 text-center text-neutral-700 dark:bg-neutral-700 dark:text-neutral-200">
            © 2023 <a class="text-neutral-800 dark:text-neutral-400" href="#">Guiline</a>
        </div>
    </footer>
</body>
</html>

guiline/core/templates/core/contact.html
{% extends "./base.html" %}
{% block title %}Contact{% endblock  %}

{% block content %}
    <h1>The contact page</h1>
{% endblock  %}

guiline/core/templates/core/index.html
{% extends "./base.html" %}
{% block title %}Welcome{% endblock  %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        <div class="grid grid-cols-4 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-xl h-64 w-full object-cover">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <div class="text-2xl">{{ item.name }}</div>
                            <p class="text-gray-500">Price: ${{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="">
                        <div class="p-6 bg-white rounded-b-xl">
                            <div class="text-2xl">{{ category.name }}</div>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock  %}

guiline/core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h2 class="mb-9 text-3xl text-center">Login</h2>
        <form action="." method="post">
            {% csrf_token %}
            
            {% comment %} ERROR HANDLING {% endcomment %}
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label> <br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label> <br>
                {{ form.password }}
            </div>

            <div class="my-3">
                <button type="submit" class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                    Login                
                </button>
            </div>
        </form>
    </div>
{% endblock  %}

guiline/core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h2 class="mb-9 text-3xl text-center">Sign up</h2>
        <form action="." method="post">
            {% csrf_token %}

            {% comment %} ERROR HANDLING {% endcomment %}
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label> <br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label> <br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label> <br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Retype Password</label> <br>
                {{ form.password2 }}
            </div>
            <div class="my-3">
                <button type="submit" class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                    Sign up
                </button>
            </div>
        </form>
    </div>
{% endblock  %}